platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/jishaowei/xiaofengCocoapodsRepo.git'

target 'MHPhotoUploader_Example' do
  pod 'MHPhotoUploader', :path => '../'

  target 'MHPhotoUploader_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
