platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/jishaowei/xiaofengCocoapodsRepo.git'

target 'MH_AlbumUploadControllerDemo' do
pod 'SDWebImage', '~> 4.4.6'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'ZLPhotoBrowser'
pod 'KSPhotoBrowser'
pod 'MHBase'
pod 'VMNetworking'
end
